# Generated by Django 4.0.2 on 2022-03-02 09:23

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
