# Generated by Django 4.0.2 on 2022-02-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_cheese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
