# Generated by Django 4.0.2 on 2022-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_default_alter_product_discontinued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='length',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.FloatField(default=100),
        ),
    ]
