# Generated by Django 4.0.2 on 2022-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_1_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_orders', models.BooleanField(default=False)),
            ],
        ),
    ]
